version: '3.7'

services:
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    image: app:latest
    volumes:
      - ./app:/usr/src/app
      - ./www:/srv/www
    ports:
      - 8000:8000
    env_file:
      - ./deploy/app.env
    depends_on:
      - db
      - redis
    restart: "unless-stopped"

  dev:
    build: ./app
    image: app:latest
    volumes:
      - ./app:/usr/src/app
      - ./www:/srv/www
      - home:/root
    env_file:
      - ./deploy/app.env

    stdin_open: true
    tty: true


  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo

  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/srv/www
    ports:
      - 8080:80

    restart: "unless-stopped"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.4.2"
    hostname: "elasticsearch"
    volumes:
    - "./elasticsearch/data:/usr/share/elasticsearch/data"
    environment:
    - 'node.name=single'
    - "node.master=true"
    - "node.data=true"
    - "node.attr.weight=heavy"
    - "cluster.name=apm.cluster"
    - "bootstrap.memory_lock=true"
    - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    - "discovery.type=single-node"
    ports:
      - "9200:9200/tcp"

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.4.2"
    hostname: "kibana"
    ports:
      - "5601:5601/tcp"

    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  apm-server:
    image: "docker.elastic.co/apm/apm-server:7.4.2"
    hostname: "apm"
    ports:
    - "8200:8200/tcp"
    environment:
      - output.elasticsearch.hosts=['http://elasticsearch:9200']
      - setup.kibana.host=kibana:5601
      - setup.template.enabled=true
      - logging.to_files=false

    depends_on:
      - elasticsearch

  redis:
    image: redis
    restart: "unless-stopped"

volumes:
  www:
  postgres_data:
  apm_es_data:
  home: